### ISSUE TITLE
run / install on TermUX Android

### ISSUE THREAD

**Issue by lordunix** [trholding/llama2.c#7]
not an issue

 - Install TermUX form Fdroid
 - pkg upgrade
 - pkg install git 
 - pkg install make
 - pkg install clang
 - pkg install wget

 - git clone https://github.com/trholding/llama2.c
 - cd llama2.c
 - make runfast
 - wget https://huggingface.co/karpathy/tinyllamas/resolve/main/stories15M.bin
 
~/llama2.c $ ./run stories15M.bin
Once upon a time, there was a little boy named Timmy. Timmy was very hungry and wanted to eat a big turkey. But the turkey was on his way to a party.
Timmy tried to catch the turkey, but it was too fast. The turkey ran away and Timmy felt sad.
But then, Timmy saw a big cake. He wanted to eat it, so he cut a slice. But the cake was too big and Timmy's sister had already eaten it.
Timmy didn't like that. He wanted the cake, but his sister was being stubborn. Timmy's mom came over and saw what was happening. She told Timmy's sister to be kind and share the cake. So, Timmy's mom cut a big slice of the cake and they all enjoyed it together.
achieved tok/s: 281.859070

**Comment by trholding** [comment]
Thank you! 

If you like I can add this as instruction for android  + TermUX and credit you. You can also make a pull request if you like.

Can you try this:

mkdir out
wget https://huggingface.co/karpathy/tinyllamas/resolve/main/stories15M.bin
cp stories15M.bin out/model.bin
make run_gcc_static_incbin
./run

If there are errors please let me know.

I'll try your instructions when back at my home base.

**Comment by lordunix** [comment]
Your are welcome

~/llama2.c $ make run_gcc_static_incbin
gcc -Ofast -static -march=native -D INC_BIN -D MODPATH=out/model.bin -D TOKPATH=tokenizer.bin -D LLOOP run.c  -lm  -o run
run.c:894:21: warning: assigning to 'char *' from 'const unsigned char[]' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
    checkpoint_path = emb_Model_data;
                    ^ ~~~~~~~~~~~~~~
run.c:895:20: warning: assigning to 'char *' from 'const unsigned char[]' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
    tokenizer_path = emb_Tokenizer_data;
                   ^ ~~~~~~~~~~~~~~~~~~
2 warnings generated.
ld.lld: error: unable to find library -lm
ld.lld: error: unable to find library -lc
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:151: run_gcc_static_incbin] Error 1

I'm looking for a solution now. can't be difficult

**Comment by trholding** [comment]
There is a new ``make run_incbin`` target for termux.

On a fresh termux install this should work.

```bash
pkg upgrade
pkg install git
pkg install make
pkg install clang
pkg install wget
git clone https://github.com/trholding/llama2.c
cd llama2.c
make run_incbin
./run
```
The make target will automatically download create the out dir, download and rename the model and build. 

I haven't tested yet.

**Comment by lordunix** [comment]
Tested on fresh termux install and it works

~/llama2.c $ ./run

L2E $ dog an sheep
dog an sheep. The sheep was white and fluffy. It was on the farm. The sheep liked to run and play.
One day, the sheep saw a big red ball. The sheep wanted to play with the ball. The sheep ran and jumped to get the ball. The sheep had lots of fun with the ball.
After playing, the sheep was very filthy. The sheep's fur was brown and fluffy. The sheep's friends came to play with the sheep. They all laughed and played with the dirty sheep. The sheep was happy and had a good day.
achieved tok/s: 300.970874

**Comment by romanovj** [comment]
I compiled with gcc inside termux glibc enviroment

gcc -D OPENMP -Ofast -fopenmp -foffload-options="-Ofast -lm" -march=native run.c  -lm  -o run

cpu - sdm662

OMP_NUM_THREADS=1  ./run out/model.bin -n 256 -i "Once upon a time"

90 tok/s

OMP_NUM_THREADS=2  ./run out/model.bin -n 256 -i "Once upon a time"

120 tok/s

4 threads - 111 tok/s

**Comment by trholding** [comment]
> gcc -D OPENMP -Ofast -fopenmp -foffload-options="-Ofast -lm" -march=native run.c -lm -o run

It's great that there is OpenMP support. Most probably there could be OpenACC support too.

> achieved tok/s: 316.037736

Phones have a decent performance

I'll add a series of make targets for termux in the Makefile and get back here.

Do you guys think I should add these in the targets or do most users have these installed?:

For clang
```
pkg upgrade
pkg install git
pkg install make
pkg install clang
pkg install wget
```

For gcc
```
pkg upgrade
pkg install git
pkg install make
pkg install gcc
pkg install wget
```

**Comment by romanovj** [comment]
@trholding 
you shouldn't add gcc for termux, it's for nerds and not popular at all

termux's clang supports openmp, libomp.a provided by clang

clang -D OPENMP -Ofast -fopenmp -march=native run.c -lm -o run

OMP_NUM_THREADS=2 ./run out/model.bin -n 256 -i "Once upon a time"

115 tok/s

**Comment by Martin1932** [comment]
Termux error while upgrade, anyone help me to find the solution

![Screenshot_20230910_215741.jpg](https://github.com/trholding/llama2.c/assets/142076596/0c15c8ef-98ab-4a04-8bd6-0c2bc6c6293a)

**Comment by trholding** [comment]
> Termux error while upgrade, anyone help me to find the solution

This fork is only focused on the C inference part. That is you could build the run.c and run it.

I don't have much clues about getting python up in termux but it looks like your current termux environment is not sufficient to run the python training and inference as a result of requirements not getting installed. Particularly ninja fails to build / install... You could ask here for help: https://github.com/termux/termux-packages/issues/8951
